### ISSUE TITLE
Include host list options

### ISSUE THREAD

**Issue by chango77747** [ChrisTruncer/WMImplant#20]
It would be nice if gen_cli included an option for a list of hosts so people don’t get confused when it asks for a single host. Below is an outline of what I had in mind:

- if the user selected gen_cli, ask the user if they want to target a single host or a multiple
- if user selected multiple hosts, ask the user for the full path to target list
- then gen_cli will output something like “gc targetList.txt | Invoke-WMImplant”

I also think it would be useful to include examples where the user passes a list of hosts in the help menu.

**Comment by ChrisTruncer** [comment]
This has been added in. It doesn't currently ask if you want to provide single or multiple, it still asks for the single system (at first) you want to run the command against. Later on, the tool asks if you would like to read in systems from a file. If that's the choice, the -ComputerName parameter is removed. It is done this way since it would require a restructure of the menu system to change when the computername is requested, and for it being only this single command, I don't mind it being the case (at the moment at least)
